Feature/Autocomplete
neolution-ch/react-hook-form-components pull request #118
Opened 2024-11-21 10:47 UTC by Michele-Masciave

2025-02-07 05:41 UTC, neotob commented on CHANGELOG.md
> +- :boom: `AsyncTypeAheadInput` based on MUI Autocomplete component.
not sure how easy and straight forward, but would it be a lot of work for a short "how to migrate" for this two components?

2025-02-07 08:06 UTC, manni497 requested changes

2025-02-07 08:06 UTC, manni497 commented on src/lib/hooks/useDebounceHook.ts
> +          } finally {
We changed this yesterday in order to solve loading issue? Or does it work like this?

2025-02-07 08:06 UTC, manni497 commented on src/lib/StaticTypeaheadInput.tsx
> +        <TextField
This code seems to be duplicated in Static and Async, I would move in a shared component

2025-02-11 09:34 UTC, neotob commented on CHANGELOG.md
> +- :boom: `AsyncTypeAheadInput` based on MUI Autocomplete component.
thank you :pray:

2025-02-12 06:53 UTC, Michele-Masciave commented on fix-autosuggest-highlight.js
> +const fs = require("fs");
Removed: it isn't needed anymore thanks to Timothy change

2025-02-12 07:18 UTC, Michele-Masciave commented on src/lib/AsyncTypeaheadInput.tsx
> +  useEffect(() => {
I've added a comment: the use effect is listening to the user actions that change the fieldValue

2025-02-12 07:18 UTC, Michele-Masciave commented on .eslintrc.cjs
> +        max: 400,
Yes I was able to to reduce to 200 chars removing some non crucial props which we can still use using "autoCompleteProps" prop

2025-02-12 07:19 UTC, Michele-Masciave commented on src/lib/types/Typeahead.ts
> +export type TypeaheadOption = LabelValueOption | string;
Mentioned ;-)

2025-02-12 07:19 UTC, Michele-Masciave commented on src/lib/hooks/useDebounceHook.ts
> +          } finally {
Changed as discussed together

2025-02-12 07:19 UTC, Michele-Masciave commented on src/lib/StaticTypeaheadInput.tsx
> +        <TextField
Extracted a common component

2025-02-19 15:30 UTC, manni497 commented
@neotob Code is now fine for me. I would suggest to wait before merging (needed for Michele in order to merge our project to devolop and check if everything is still fine). What do you think? Do you agree?

2025-03-03 07:40 UTC, manni497 approved these changes

2025-03-03 08:55 UTC, merged