Added disabled and selected option for select input
neolution-ch/react-hook-form-components pull request #68
Opened 2023-08-31 09:11 UTC by severinoAmmirati

Added disabled and selected option for select input

2023-08-31 10:01 UTC, neotrow requested changes
@severinoAmmirati 

Thanks for the PR 🙏 


@neotob 
As I am on holidays soon, could you take over for the rest of the review? Thanks 🙏

2023-08-31 12:19 UTC, severinoAmmirati commented on src/lib/types/LabelValueOption.ts
>  interface LabelValueOption {
@neotob Seems that the disabled prop is already implemented in the Static/AsyncTypeahead. I've added some cypress test to them

2023-08-31 12:20 UTC, severinoAmmirati commented on cypress/cypress/component/Input/Select.cy.tsx
> +    <Form
Test removed, as suggested, selected can be replaced by `defaultValues`

2023-08-31 12:21 UTC, severinoAmmirati commented on src/lib/types/LabelValueOption.ts
> +  selected?: boolean;
Not currently, so it was removed

2023-09-04 09:38 UTC, neotob commented on src/lib/types/LabelValueOption.ts
>  interface LabelValueOption {
thanks for adding the tests!

2023-09-11 13:56 UTC, merged